export const FILTER_CHANGE = 'DE_FILTER_CHANGE';
export const SIZE_CHANGE = 'DE_SIZE_CHANGE';
export const STRIDE_CHANGE = 'DE_STRIDE_CHANGE';
export const ACTIVATION_CHANGE = 'DE_ACTIVATION_CHANGE';
